FROM node:16.13.0-alpine AS builder
WORKDIR /usr/src/app
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake
COPY package*.json ./
COPY prisma ./prisma/
RUN yarn
RUN yarn add global ts-node
RUN npx prisma generate
COPY . ./
RUN yarn run env:staging
RUN yarn run build
CMD [ "sh", "-c", "NODE_ENV=staging yarn run start:prod"]
