export const SecretKeys = {
  DATABASE_URL: {
    staging: 'DATABASE_URL_STAGING',
  },
  GOOGLE_OAUTH_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID',
  GOOGLE_OAUTH_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
  JWT_SECRET: 'JWT_SECRET',
};
